######################################
# Media Rules
######################################

  - alias: Harmony Hub Playing Content
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_select.basement_tv
        to: 'Watch TV on Xbox'
      - platform: state
        entity_id: input_select.basement_tv
        to: 'Cast to TV'
    action:
        service: scene.turn_on
        entity_id: scene.netflix_and_chill

######################################
# Lighting Rules 
######################################

  - alias: Enable First Morning Trigger
    trigger:
      - platform: time
        after: '4:00'
    action: 
      service: homeassistant.turn_on
      entity_id: input_boolean.trigger_first_morning

  - alias: Basement lights auto off
    trigger:
        platform: state
        entity_id: binary_sensor.downstairs_occupancy
        state: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.maya_basement_outlet_switch_14_0, light.rear_basement_lights_level_8_0, light.front_basement_lights_level_9_0, light.basement_stairs, light.basement_accent
      - service: notify.notify_manna
        data:
          title: 'Auto off - Basement Lights'
          message: 'Basement lights turned off'
    condition:
      - condition: and
        conditions:
          - condition: template
            value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
          - condition: or
            conditions:
              - condition: state
                entity_id: light.basement_accent
                state: 'on'
              - condition: state
                entity_id: light.basement_stairs
                state: 'on'
              - condition: state
                entity_id: light.front_basement_lights_levl_9_0
                state: 'on'
              - condition: state
                entity_id: light.rear_basement_lights_level_8_0
                state: 'on'
              - condition: state
                entity_id: switch.maya_basement_outlet_switch_14_0
                state: 'on'

  - alias: Office lights auto off
    trigger:
        platform: state
        entity_id: binary_sensor.office_occupancy
        state: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: light.office_ceiling
      - service: notify.notify_manna
        data:
          title: 'Auto off - Office Lights'
          message: 'Office lights turned off'
    condition:
        condition: state
        entity_id: light.office_ceiling
        state: 'on'

  - alias: Turn on lights when sun sets
    initial_state: True
    hide_entity: False
    trigger:    
        platform: sun
        event: sunset
    action:
        service: homeassistant.turn_on
        entity_id: light.living_room, scene.outdoor

  - alias: Mayas Basement Light Auto On
    initial_state: True
    hide_entity: False
    trigger:
        platform: state
        entity_id: binary_sensor.downstairs_occupancy
        state: "on"
    action:
        service: homeassistant.turn_on
        entity_id: switch.maya_basement_outlet_switch_14_0

  - alias: Lights off at sunrise
    initial_state: True
    hide_entity: False
    trigger:    
        platform: sun
        event: sunrise
    action:
      - service: light.turn_off
        entity_id: light.side_door_light_level_11_0, light.aeotec_zw098_led_bulb_level_2_0, light.backyard_lights_level_13_0, light.living_room, light.mayas_bedroom
      - service: notify.notify_manna
        data:
          title: 'Sunrise'
          message: 'Daylight is burning!'

  - alias: Mayas Night Light
    initial_state: True
    hide_entity: False
    trigger:
        platform: time
        after: '18:00'
    action:
        service: light.turn_on
        entity_id: light.mayas_bedroom

  - alias: Goodnight
    trigger:
        platform: event
        event_type: call_service
        event_data:
          service_data:
            entity_id: scene.goodnight
          domain: scene
          service: turn_on
    action:
        service: climate.set_temperature
        data:
          entity_id: climate.mannabee
          temperature: 64
          target_temp_high: 66
          target_temp_low: 63

  - alias: Good morning
    initial_state: True
    hide_entity: False
    trigger:    
        platform: state
        entity_id: light.living_room
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.trigger_first_morning
        state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.goodmorning
      - service: homeassistant.turn_off
        entity_id: input_boolean.trigger_first_morning
      - service: notify.notify_manna
        data:
          title: 'Good morning'
          message: 'My girls are up!'

######################################
# Away Mode
######################################

  - alias: Away After Sunset
    trigger:
      - platform: state
        entity_id: input_boolean.trigger_away_mode
        state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.away_after_sunset
      - service: climate.set_away_mode
        data:
          entity_id: climate.mannabee
          away_mode: true
      - service: notify.notify_manna
        data:
          title: 'ecoSB afSunset'
          message: 'ecobSB + nlight'
    condition:
        condition: state
        entity_id: sun.sun
        state: 'below_horizon'

  - alias: Away Before Sunset
    trigger:
      - platform: state
        entity_id: input_boolean.trigger_away_mode
        state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.away_before_sunset
      - service: climate.set_away_mode
        data:
          entity_id: climate.mannabee
          away_mode: true
      - service: notify.notify_manna
        data:
          title: 'ecoSB bfSunset'
          message: 'ecobSB + lights off'
    condition:
        condition: state
        entity_id: sun.sun
        state: 'above_horizon'

  - alias: Ecobee Triggered Away After Sunset
    trigger:
      - platform: state
        entity_id: sensor.away_mode
        state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.away_after_sunset
      - service: notify.notify_manna
        data:
          title: 'ecoSB afSunset'
          message: 'ecobSB + nlight'
    condition:
        condition: state
        entity_id: sun.sun
        state: 'below_horizon'

  - alias: Ecobee Triggered Away Before Sunset
    trigger:
        platform: state
        entity_id: sensor.away_mode
        state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.away_before_sunset
      - service: climate.set_away_mode
        data:
          entity_id: climate.mannabee
          away_mode: true
      - service: notify.notify_manna
        data:
          title: 'ecoSB bfSunset'
          message: 'ecobSB + lights off'
    condition:
        condition: state
        entity_id: sun.sun
        state: 'above_horizon'

  - alias: Check Away Mode at  Sunset
    initial_state: True
    hide_entity: False
    trigger:
        platform: state
        entity_id: sun.sun
        to: 'below_horizon'
    action:
      - service: scene.turn_on
        entity_id: scene.away_after_sunset
      - service: notify.notify_manna
        data:
          message: 'Away lighting scene turned on'
    condition:
        condition: and
        conditions: 
          - condition: state
            entity_id: sensor.away_mode
            state: 'on'
          - condition: state
            entity_id: light.dining_room_light_level_6_0
            state: 'off'

######################################
# Harmony Hub
######################################

  - alias: 'Harmony activity through HA'
    trigger:
      platform: state
      entity_id: input_select.basement_tv
    action:
      service: script.turn_on
      entity_id: script.input_select_harmony

  - alias: "Watch TV started from Harmony Hub"
    trigger:
      platform: state
      entity_id: remote.basement_harmony
    condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "Watch TV on Xbox" }}'
    action:
      service: input_select.select_option
      entity_id: input_select.basement_tv
      data:
        option: "Watch TV on Xbox"

  - alias: "Cast started from Harmony Hub"
    trigger:
      platform: state
      entity_id: remote.basement_harmony
    condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "Cast to TV" }}'
    action:
      service: input_select.select_option
      entity_id: input_select.basement_tv
      data:
        option: "Cast to TV"

######################################
# Z-Wave
######################################

  - alias: zwave heal at 2:30am
    trigger:
      platform: time
      after: '2:30:00'
    action:
      service: zwave.heal_network

######################################
# Dynamic UI
######################################

  - alias: Show Outdoor Light View
    trigger:
      - platform: sun
        event: sunset
    action:
      service: group.set_visibility
      entity_id: group.outdoor_lights
      data:
        visible: True

  - alias: Hide Outdoor Light View
    trigger:
      - platform: sun
        event: sunrise
        offset: '00:45:00'
      - platform: event
        event_type: homeassistant_start
    action:
      service: group.set_visibility
      entity_id: group.outdoor_lights       
      data:
        visible: False

  - alias: 'Hide living room chromecast while not playing'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: media_player.living_room
        state: 'off'
      - platform: event
        event_type: homeassistant_start
    action:
      service: group.set_visibility
      entity_id: group.livingroom_cast
      data:
        visible: False

  - alias: 'Show livingroom chromecast while playing'
    hide_entity: true
    trigger:
      platform: state
      entity_id: media_player.living_room
      state: 'playing'
    action:
      service: group.set_visibility
      entity_id: group.livingroom_cast
      data:
        visible: True

  - alias: 'Hide Roku while not playing'
    trigger:
      - platform: state
        entity_id: media_player.manna_roku
        state: 'home'
      - platform: event
        event_type: homeassistant_start
    action:
      service: group.set_visibility
      entity_id: group.livingroom_roku
      data:
        visible: False

  - alias: 'Show Roku while not playing'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: media_player.manna_roku
        state: 'playing'
    action:
      service: group.set_visibility
      entity_id: group.livingroom_roku
      data:
        visible: True
