homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: <secret>
  longitude: <secret>
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: <secret>
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize:
    media_player.living_room:
      friendly_name: Living Room Chromecast
    configurator.plex_media_server:
      hidden: true
    media_player.plex_web_chrome:
      hidden: true
    media_player.roku_1gh33k009150:
      friendly_name: Living Room Roku
    switch.kitchen_hallway_switch_7_0:
      friendly_name: Kitchen Hallway Light
    light.living_room:
      friendly_name: Living Room Light
    light.kitchen_lights_level_5_0:
      friendly_name: Kitchen Lights
    light.kitchen_sink_light_level_4_0:
      friendly_name: Kitchen Sink Light
    light.dining_room_light_level_6_0:
      friendly_name: Dining Room Light
    light.front_basement_lights_level_9_0:
      friendly_name: Front Basement Lights
    light.rear_basement_lights_level_8_0:
      friendly_name: Back Basement Lights
    light.side_door_light_level_11_0:
      friendly_name: Side Door Light
    light.backyard_lights_level_13_0:
      friendly_name: Backyard Lights
    light.aeotec_zw098_led_bulb_level_2_0:
      friendly_name: Porch Light
    light.pendant_lights_level_3_0:
      friendly_name: Pendant Light
    switch.wemo_switch:
      friendly_name: Mayas Basement Light
    media_player.kitchen:
      friendly_name: Kitchen Sonos
      icon: mdi:speaker-wireless
    media_player.basement:
      friendly_name: Basement Sonos
      icon: mdi:speaker-wireless
    media_player.basement_vizio:
      friendly_name: Vizio Cast
      icon: mdi:cast
    binary_sensor.kitchen_nest_protect_online:
      friendly_name: Kitchen Protect
      icon: mdi:nest-protect
    binary_sensor.upstairs_nest_protect_online:
      friendly_name: Kitchen Protect
      icon: mdi:nest-protect
    scene.netflix_and_chill:
      icon: mdi:sofa
      friendly_name: Movie Scene
    scene.goodnight:
      icon: mdi:sleep
    scene.goodmorning:
      icon: mdi:white-balance-sunny
    scene.first_floor_nightlight:
      icon: mdi:brightness-2
    scene.outdoor:
      icon: mdi:terrain
    sensor.current_activity:
      icon: mdi:cast-connected

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  include:
    entities:
      - sensor.living_room_temperature
      - sensor.mannabee_temperature
      - sensor.mayas_bedroom_temperature
      - sensor.office_temperature
      - sensor.kitchen_temperature
      - sensor.downstairs_temperature
      - sensor.mannabee_humidity
      - light.aeotec_zw098_led_bulb_level_2_0
      - light.pendant_lights_level_3_0
      - light.kitchen_sink_light_level_4_0
      - light.kitchen_lights_level_5_0
      - light.dining_room_light_level_6_0
      - light.rear_basement_lights_level_8_0
      - light.front_basement_lights_level_9_0
      - light.side_door_light_level_11_0
      - light.living_room
      - light.master_bedroom
      - light.mayas_bedroom
      - light.backyard_lights_level_13_0
      - switch.wemo_switch
      - switch.kitchen_hallway_switch_7_0
      - automation.basement_lights_auto_off
      - automation.good_morning
      - automation.lights_off_at_sunrise
      - automation.office_lights_auto_off
      - automation.turn_on_lights_when_sun_sets
      - binary_sensor.downstairs_occupancy
      - binary_sensor.kitchen_occupancy
      - binary_sensor.living_room_occupancy
      - binary_sensor.mannabee_occupancy
      - binary_sensor.mayas_bedroom_occupancy
      - binary_sensor.office_occupancy

recorder:
    purge_days: 10

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_humidity
      - sensor.dark_sky_icon
      - sensor.dark_sky_ozone
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
  include:
    domains:
      - binary_sensor
      - automation
      - sensor
      - light
      - media_player
      - switch
     
# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: darksky
    api_key: <secret>
    monitored_conditions:
      - summary
      - icon
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - ozone
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
    update_interval: '01:00'
  - platform: plex
    host: <secret>
    port: <secret>
    username: <secret>
    password: <secret>
  - platform: template
    sensors:
      away_mode:
        friendly_name: 'HVAC Mode'
        value_template: "{{ states.climate.mannabee.attributes.away_mode }}"
  - platform: template
    sensors:
      current_activity:
        friendly_name: 'Current Harmony Status'
        value_template: '{{ states.remote.basement_harmony.attributes.current_activity }}'

# Text to speech
tts:
  platform: google

input_boolean:
  trigger_first_morning:
    name: Waiting for first morning motion
    icon: mdi:kettle
  trigger_away_mode:
    name: Away Mode
    icon: mdi:telegram

input_select:
  basement_tv:
    name: Basement Harmony Control
    options:
      - PowerOff
      - Watch TV on Xbox
      - Cast to TV
      - Listen to Basement Sonos
    initial: PowerOff
    icon: mdi:monitor

script: !include script.yaml

automation: !include automation.yaml

scene: !include scenes.yaml

group: !include group.yaml

light:
  platform: hue
  host: <secret>
  allow_unreachable: true

media_player:
  - platform: sonos
  - platform: plex
  - platform: cast
  - platform: roku

mqtt:
  broker: <secret>
  port: 1883
  client_id: home-assistant-1
  username: <secret>
  password: <secret>

zwave:
  usb_path: /dev/ttyAMA0
  polling_interval: 90000
  autoheal: false

ecobee:
  api_key: <secret>

climate:
  platform: ecobee

nest:
  client_id: <secret>
  client_secret: <secret>

emulated_hue:
  type: alexa
  host_ip: <secret>
  listen_port: 8300
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - light
    - scene
    - script

notify:
  - name: notify_manna
    platform: pushbullet
    api_key: <secret>

remote:
  - platform: harmony
    name: Basement Harmony
    host: <secret>

device_tracker:
  - platform: nmap_tracker
    hosts: <secret>
    home_interval: 10
