homeassistant:
  name: REDACTED Abode
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:account-multiple
  
frontend:
  javascript_version: latest
  themes: !include themes.yaml

config:
  
sensor: !include sensors.yaml

input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml

switch: !include switch.yaml

script: !include scripts.yaml

automation: !include automations.yaml

scene: !include scenes.yaml

group: !include groups.yaml
  
http:
  api_password: !secret api_password
  trusted_networks:
    - REDACTED.6
    - REDACTED.7
# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history: !include history.yaml

recorder:
  purge_interval: 2
  purge_keep_days: 14

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_humidity
      - sensor.dark_sky_icon
      - sensor.dark_sky_ozone
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
  include:
    domains:
      - binary_sensor
      - automation
      - sensor
      - light
      - media_player
      - switch
     
# Track the sun

sun:

tts:
  platform: google

wemo:
  static:
    - REDACTED.28
    - REDACTED.29

hue:
  bridges:
  - host: REDACTED.23
    allow_unreachable: true
    allow_hue_groups: false

media_player:
  - platform: roku

sonos:
  media_player:
    hosts:
      - REDACTED.8
      - REDACTED.9
      - REDACTED.10

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  polling_interval: 90000
  autoheal: false
  device_config:
    light.rear_basement_lights_level:
      refresh_value: true
      polling_intensity: 1
    light.front_basement_light_level:
      refresh_value: true
      polling_intensity: 1
    light.pendant_lights_level:
      refresh_value: true
      polling_intensity: 1
    light.kitchen_sink_light_level:
      refresh_value: true
      polling_intensity: 1
    light.kitchen_can_lights_level:
      refresh_value: true
      polling_intensity: 1
    light.dining_room_light_level:
      refresh_value: true
      polling_intensity: 1
    light.stairwell_ight_level:
      refresh_value: true
      polling_intensity: 1
    light.upstairs_hallway_light_level:
      refresh_value: true
      polling_intensity: 1 

ecobee:
  api_key: !secret ecobee_api
  hold_temp: true

climate:
  platform: ecobee

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

emulated_hue:
  host_ip: REDACTED.73
  listen_port: 8300
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false

#homekit:
#  filter:
#    include_domains:
#      - light
#      - media_player
#  entity_config:
#    light.kitchen_can_lights_level:
#      name: Kitchen Lights
#    light.kitchen_sink_light_level:
#      name: Kitchen Sink Light
#    light.dining_room_light_level:
#      name: Dining Room Light
#    light.front_basement_light_level:
#      name: Front Basement Lights
#    light.rear_basement_lights_level:
#      name: Back Basement Lights
#    light.side_door_light_level:
#      name: Side Door Light
#    light.backyard_lights_level:
#      name: Backyard Lights
#    light.aeotec_zw098_led_bulb_level:
#      name: Furnace Room Light
#    light.pendant_lights_level:
#      name: Pendant Light
#    light.back_door_light_level:
#      name: Back Door Light
#    light.upstairs_hallway_light_level:
#      name: Upstairs Hallway Light
#    light.stairway_light_level:
#      name: Stairway Light

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api
    name: REDACTED_pushbullet
  - platform: ios
  - name: notify_REDACTED
    platform: group
    services:
      - service: ios_REDACTED_iphone
      - service: ios_REDACTED_iphone
      - service: REDACTED_pushbullet

remote:
  - platform: harmony
    name: Basement Harmony
  - platform: harmony
    name: Living Room Harmony

device_tracker:
  - platform: unifi
    host: REDACTED.73
    username: !secret unifi_user
    password: !secret unifi_pass
    consider_home: 300
    interval_seconds: 12
    verify_ssl: false


ios:
  push:
    categories:
      - name: lightsoff
        identifier: 'lightsoff'
        actions:
          - identifier: 'BASEMENT_LIGHTS_OFF'
            title: 'Turn Off Basement Lights'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'

camera:
  - platform: amcrest

amcrest:
  - host: REDACTED.25
    username: !secret amcrest1_user
    password: !secret amcrest1_pass
    resolution: high
  - host: REDACTED.26
    username: !secret amcrest2_user
    password: !secret amcrest2_pass
    resolution: high

influxdb:
  host: REDACTED.73
  database: home_assistant
