homeassistant:
  name: REDACTED
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret api_password
   - type: trusted_networks
     trusted_networks:
       - REDACTED.6
       - REDACTED.7

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:account-multiple
  
frontend:
  themes: !include themes.yaml

lovelace:
  mode: yaml

sensor: !include sensors.yaml

input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml

switch: !include switch.yaml

script: !include scripts.yaml

automation: !include automations.yaml

scene: !include scenes.yaml

group: !include groups.yaml

#http:
#  api_password: !secret api_password
#  trusted_networks:
#    - REDACTED.6
#    - REDACTED.7
# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - philips_hue

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history: !include history.yaml

recorder:
  purge_interval: 2
  purge_keep_days: 14

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_humidity
      - sensor.dark_sky_icon
      - sensor.dark_sky_ozone
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
  include:
    domains:
      - binary_sensor
      - automation
      - sensor
      - light
      - media_player
      - switch
     
# Track the sun

sun:

# Weather Prediction

tts:
  platform: google

wemo:
  discovery: false
  static:
    - REDACTED.XX
    - REDACTED.XX
    - REDACTED.XX

hue:
  bridges:
  - host: REDACTED.XX
    allow_unreachable: true
    allow_hue_groups: false

tplink:
  discovery: false
  switch:
    - host: REDACTED.XX
    - host: REDACTED.XX

media_player:
  - platform: roku

sonos:
  media_player:
    hosts:
      - REDACTED.XX
      - REDACTED.XX
      - REDACTED.XX
      - REDACTED.XX

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  polling_interval: 90000
  autoheal: false
  device_config:
    light.rear_basement_lights_level:
      refresh_value: true
      polling_intensity: 1
    light.front_basement_light_level:
      refresh_value: true
      polling_intensity: 1
    light.pendant_lights_level:
      refresh_value: true
      polling_intensity: 1
    light.kitchen_sink_light_level:
      refresh_value: true
      polling_intensity: 1
    light.kitchen_can_lights_level:
      refresh_value: true
      polling_intensity: 1
    light.dining_room_light_level:
      refresh_value: true
      polling_intensity: 1
    light.stairwell_light_level:
      refresh_value: true
      polling_intensity: 1
    light.upstairs_hallway_light_level:
      refresh_value: true
      polling_intensity: 1
    switch.outdoor_switch:
      refresh_value: true
      polling_intensity: 1
    fan.office:
      refresh_value: true
      polling_intensity: 1

ecobee:
  api_key: !secret ecobee_api
  hold_temp: true

climate:
  platform: ecobee

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

emulated_hue:
  host_ip: REDACTED.XX
  listen_port: 8300
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false

homekit:
  auto_start: False
  filter:
    include_entities:
      - light.kitchen_can_lights_level
      - light.kitchen_sink_light_level
      - light.dining_room_light_level
      - light.front_basement_light_level
      - light.rear_basement_lights_level
      - light.backyard_lights_level
      - light.side_door_light_level
      - light.back_door_light_level
      - light.furnace_room_light_level
      - light.pendant_lights_level
      - light.upstairs_hallway_light_level
      - light.stairwell_light_level
      - light.builtin
      - lock.front_door_lock
      - switch.garage_door_switch
      - input_boolean.trigger_away_mode
      - input_boolean.trigger_alarm_mode
      - input_boolean.trigger_goodnight
      - input_boolean.turn_off_computer
      - input_boolean.trigger_girls_bedtime_routine
      - input_boolean.turn_on_living_room_roku
      - input_boolean.turn_off_living_room_tv
      - input_boolean.turn_on_xbox
      - input_boolean.turn_off_basement_tv
      - switch.basement_switch
      - switch.kitchen_hallway_light
      - switch.wemo_switch
      - switch.mayas_humidifier
      - switch.morgans_humidifier
      - switch.outdoor_switch
      - switch.wemomini1
  entity_config:
    light.kitchen_can_lights_level:
      name: Kitchen Lights
    light.kitchen_sink_light_level:
      name: Kitchen Sink Light
    light.dining_room_light_level:
      name: Dining Room Light
    light.front_basement_light_level:
      name: Front Basement Lights
    light.rear_basement_lights_level:
      name: Back Basement Lights
    light.side_door_light_level:
      name: Side Door Light
    light.backyard_lights_level:
      name: Backyard Lights
    light.furnace_room_light_level:
      name: Furnace Room Light
    light.pendant_lights_level:
      name: Pendant Light
    light.back_door_light_level:
      name: Back Door Light
    light.upstairs_hallway_light_level:
      name: Upstairs Hallway Light
    light.stairwell_light_level:
      name: Stairway Light
    light.builtin:
      name: Built-in
    lock.front_door_lock:
      name: Front Door Lock
      code: 1325
    switch.garage_door_switch:
      name: Garage Door
    switch.outdoor_switch:
      name: Outdoor Switch
    switch.wemomini1:
      name: Printer
    input_boolean.trigger_away_mode:
      name: Away mode
    input_boolean.trigger_alarm_mode:
      name: Alarm mode
    input_boolean.trigger_goodnight:
      name: Goodnight
    input_boolean.trigger_girls_bedtime_routine:
      name: Girls bedtime routine
    input_boolean.turn_on_living_room_roku:
      name: Living Room Roku
    input_boolean.turn_off_living_room_tv:
      name: Living Room TV Off

notify:
  - name: REDACTED_pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api
  - name: ios_group
    platform: group
    services:
      - service: ios_REDACTEDs_iphone
      - service: ios_REDACTEDs_iphone

remote:
  - platform: harmony
    name: Basement Harmony
  - platform: harmony
    name: Living Room Harmony

device_tracker:
  - platform: unifi
    host: REDACTED.XX
    port: 8443
    username: !secret unifi_user
    password: !secret unifi_pass
    site_id: REDACTED
    consider_home: 300
    interval_seconds: 12
    verify_ssl: false

config:

system_health:

ios:
  push:
    categories:
      - name: lightsoff
        identifier: 'lightsoff'
        actions:
          - identifier: 'BASEMENT_LIGHTS_OFF'
            title: 'Turn Off Basement Lights'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'

camera:
  - platform: amcrest
  - platform: mjpeg
    mjpeg_url: http://REDACTED.59:8081/
    name: officecamera
    username: !secret officecam_user
    password: !secret officecam_pass

amcrest:
#  - host: REDACTED.25
#    username: !secret mayacamera_user
#    password: !secret mayacamera_pass
#    name: mayacamera
#    resolution: high
#    sensors:
#      - motion_detector
  - host: REDACTED.XX
    username: !secret morgancamera_user
    password: !secret morgancamera_pass
    name: morgancamera
    resolution: high
    sensors:
      - motion_detector
  - host: REDACTED.XX
    username: !secret drivewaycamera_user
    password: !secret drivewaycamera_pass
    name: drivewaycamera
    resolution: high
    sensors:
      - motion_detector


influxdb:
  host: REDACTED.XX
  database: home_assistant
